### ISSUE TITLE
Cadical crashes when only one literal is passed in a clause from CBMC

### ISSUE THREAD

**Issue by srogatch** [arminbiere/cadical#41]
I have compiled Cadical 1.5.2 inside CBMC with `make -C src CADICAL=/path/to/latest/master`.
However now the program crashes. After enabling `assert`s in Cadical, I can see the following failure:
`cbmc: ../src/clause.hpp:113: static size_t CaDiCaL::Clause::bytes(int): Assertion `size > 1' failed.`
So it seems that CBMC passes to Cadical a clause containing only 1 literal.
The code that fails is:
```
  static size_t bytes (int size) {

    // Memory sanitizer insists that clauses put into consecutive memory in
    // the arena are still 8 byte aligned.  We could also allocate 8 byte
    // aligned memory there.  However, assuming the real memory foot print
    // of a clause is 8 bytes anyhow, we just allocate 8 byte aligned memory
    // all the time (even if allocated outside of the arena).
    //
    assert (size > 1);
    return align ((size - 2) * sizeof (int) + sizeof (Clause), 8);
  }
```
So obviously this leads to a crash at runtime because 1-2=-1, and then too little memory is allocated.
I understand that 1-literal clause leads to formula simplification, but CBMC doesn't seem to do this. Can Cadical do the simplification?

**Comment by srogatch** [comment]
I ran the program again and now I realize that may be not the problem in the first instance. It looks like something corrupts the memory. Below is a new assertion failure and the stack trace:
```
Solving with CaDiCaL 1.5.2
6349523 variables, 39638459 clauses
cbmc: ../src/radix.hpp:139: void CaDiCaL::rsort(I, I, Rank) [I = __gnu_cxx::__normal_iterator<CaDiCaL::Clause **, std::vector<CaDiCaL::Clause *>>, Rank = CaDiCaL::pointer_rank]: Assertion `rank (p[0]) <= rank (p[1])' failed.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a29859 in __GI_abort () at abort.c:79
#2  0x00007ffff7a29729 in __assert_fail_base (fmt=0x7ffff7bbf588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x2250660 <str> "rank (p[0]) <= rank (p[1])", file=0x220caf0 "../src/radix.hpp", 
    line=139, function=<optimized out>) at assert.c:92
#3  0x00007ffff7a3af36 in __GI___assert_fail (assertion=0x2250660 <str> "rank (p[0]) <= rank (p[1])", file=0x220caf0 "../src/radix.hpp", line=139, 
    function=0x2250580 <__PRETTY_FUNCTION__._ZN7CaDiCaL5rsortIN9__gnu_cxx17__normal_iteratorIPPNS_6ClauseESt6vectorIS4_SaIS4_EEEENS_12pointer_rankEEEvT_SB_T0_> "void CaDiCaL::rsort(I, I, Rank) [I = __gnu_cxx::__normal_iterator<CaDiCaL::Clause **, std::vector<CaDiCaL::Clause *>>, Rank = CaDiCaL::pointer_rank]") at assert.c:101
#4  0x0000000001a4991f in CaDiCaL::rsort<__gnu_cxx::__normal_iterator<CaDiCaL::Clause**, std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> > >, CaDiCaL::pointer_rank> (
    first=0x7fff92527fb0, last=0x7fff6c869a10, rank=...) at ../src/radix.hpp:139
#5  0x0000000001a46a71 in CaDiCaL::Internal::copy_non_garbage_clauses (this=<optimized out>) at ../src/collect.cpp:371
#6  0x0000000001a47927 in CaDiCaL::Internal::garbage_collection (this=0x623000000100) at ../src/collect.cpp:420
#7  0x00000000019b9ae8 in CaDiCaL::Internal::reduce (this=<optimized out>) at ../src/reduce.cpp:181
#8  0x000000000190f60a in CaDiCaL::Internal::cdcl_loop_with_inprocessing (this=<optimized out>, this@entry=0x623000000100) at ../src/internal.cpp:209
#9  0x00000000019139b9 in CaDiCaL::Internal::solve (this=0x623000000100, preprocess_only=false) at ../src/internal.cpp:598
#10 0x000000000190261a in CaDiCaL::External::solve (this=0x6130000003c0, preprocess_only=false) at ../src/external.cpp:268
#11 0x00000000017cd547 in CaDiCaL::Solver::call_external_solve_and_check_results (this=<optimized out>, preprocess_only=false) at ../src/solver.cpp:602
#12 0x000000000151db74 in satcheck_cadicalt::do_prop_solve() () at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:919
#13 0x0000000001676a90 in prop_conv_solvert::dec_solve (this=<optimized out>) at prop/prop_conv_solver.cpp:456
#14 0x0000000001150a83 in run_property_decider (result=..., properties=..., property_decider=..., ui_message_handler=..., solver_runtime=..., set_pass=<optimized out>) at bmc_util.cpp:404
#15 0x0000000001163327 in multi_path_symex_checkert::operator() (this=<optimized out>, properties=...) at multi_path_symex_checker.cpp:68
#16 0x0000000000cb259b in all_properties_verifier_with_trace_storaget<multi_path_symex_checkert>::operator() (this=0x620000003080) at ../goto-checker/all_properties_verifier_with_trace_storage.h:43
#17 0x0000000000c974e2 in cbmc_parse_optionst::doit (this=0x7fffffffd860) at cbmc_parse_options.cpp:778
#18 0x0000000001ae2fef in parse_options_baset::main (this=0x7fffffffd860) at parse_options.cpp:100
#19 0x0000000000c84fe7 in main (argc=-10176, argv=0x10007fff7b08) at cbmc_main.cpp:48
```

**Comment by krobelus** [comment]
Since you suspect memory corruption, can you try with address sanitizer (`./configure CXXFLAGS=-fsanitize=address`)?
Maybe also try simplifying this (huge) formula by preprocessing it with something like `lingeling -O10 --clim=10000`.
If that doesn't work (anymore), delta debugging can help.
There is cnfdd from http://fmv.jku.at/cnfuzzdd/ though I haven't used that one. Even a really primitive script that deletes random lines could work well here.

**Comment by srogatch** [comment]
I'm already building&running with Address and Undefined sanitizers in `clang-13`. This is the first error that gets found. I'm now trying a different implementation of Radix Sort.

**Comment by srogatch** [comment]
After changing/fixing the radix sort, I got a new stack tract:
```
Solving with CaDiCaL 1.5.2
6349523 variables, 39638459 clauses

Program received signal SIGSEGV, Segmentation fault.
0x0000000000811369 in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) ()
(gdb) bt
#0  0x0000000000811369 in __asan::Allocator::Allocate(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType, bool) ()
#1  0x0000000000811c5a in __asan::asan_memalign(unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) ()
#2  0x00000000008be5f3 in operator new(unsigned long) ()
#3  0x00000000017dfde9 in __gnu_cxx::new_allocator<int>::allocate (this=<optimized out>, __n=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/new_allocator.h:121
#4  std::allocator_traits<std::allocator<int> >::allocate (__a=..., __n=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:460
#5  std::_Vector_base<int, std::allocator<int> >::_M_allocate (this=<optimized out>, __n=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:346
#6  0x00000000018f1d37 in std::vector<int, std::allocator<int> >::_M_realloc_insert<int const&> (this=0x7ffeda48b758, this@entry=0xffe77bfe, __position=non-dereferenceable iterator for std::vector, 
    __args=@0x7fffffff81a0: -1606658) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/vector.tcc:440
#7  0x00000000018f1bf0 in std::vector<int, std::allocator<int> >::push_back (this=<optimized out>, __x=@0x623000000390: 0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:1198
#8  0x00000000019d1cda in CaDiCaL::Internal::subsume_round (this=0x623000000100) at ../src/subsume.cpp:522
#9  0x00000000019d3feb in CaDiCaL::Internal::subsume (this=0x623000000100, update_limits=false) at ../src/subsume.cpp:586
#10 0x0000000001a7999d in CaDiCaL::Internal::elim (this=<optimized out>, update_limits=<optimized out>) at ../src/elim.cpp:846
#11 0x000000000190f664 in CaDiCaL::Internal::cdcl_loop_with_inprocessing (this=<optimized out>, this@entry=0x623000000100) at ../src/internal.cpp:212
#12 0x00000000019139b9 in CaDiCaL::Internal::solve (this=0x623000000100, preprocess_only=false) at ../src/internal.cpp:598
#13 0x000000000190261a in CaDiCaL::External::solve (this=0x6130000003c0, preprocess_only=false) at ../src/external.cpp:268
#14 0x00000000017cd547 in CaDiCaL::Solver::call_external_solve_and_check_results (this=<optimized out>, preprocess_only=false) at ../src/solver.cpp:602
#15 0x000000000151db74 in satcheck_cadicalt::do_prop_solve() () at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:919
#16 0x0000000001676a90 in prop_conv_solvert::dec_solve (this=<optimized out>) at prop/prop_conv_solver.cpp:456
#17 0x0000000001150a83 in run_property_decider (result=..., properties=..., property_decider=..., ui_message_handler=..., solver_runtime=..., set_pass=<optimized out>) at bmc_util.cpp:404
#18 0x0000000001163327 in multi_path_symex_checkert::operator() (this=<optimized out>, properties=...) at multi_path_symex_checker.cpp:68
#19 0x0000000000cb259b in all_properties_verifier_with_trace_storaget<multi_path_symex_checkert>::operator() (this=0x620000003080) at ../goto-checker/all_properties_verifier_with_trace_storage.h:43
#20 0x0000000000c974e2 in cbmc_parse_optionst::doit (this=0x7fffffffd860) at cbmc_parse_options.cpp:778
#21 0x0000000001ae7a2f in parse_options_baset::main (this=0x7fffffffd860) at parse_options.cpp:100
#22 0x0000000000c84fe7 in main (argc=-10176, argv=0x10007fff7b08) at cbmc_main.cpp:48
```

**Comment by krobelus** [comment]
On Mon, Nov 01, 2021 at 05:43:25PM -0700, Serge Rogatch wrote:
> After changing/fixing the radix sort, I got a new stack tract:
> 
> #5  std::_Vector_base<int, std::allocator<int> >::_M_allocate (this=<optimized out>, __n=<optimized out>) at /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:346
> #6  0x00000000018f1d37 in std::vector<int, std::allocator<int> >::_M_realloc_insert<int const&> (this=0x7ffeda48b758, ***@***.***=0xffe77bfe, __position=non-dereferenceable iterator for std::vector, 

Right, ASan can't detect if we are corrupting the data structures used by malloc

**Comment by arminbiere** [comment]
You can use 'valgrind' too.

Furthermore, if you send me the API trace (set CADICAL_API_TRACE environment variable to a file for the trace) then I can debug this without your CBMC set-up assuming you only have one CaDiCaL instance.

**Comment by arminbiere** [comment]
Another thought.  If you are linking against pthread, then the C++/C stack is more limited.  You could play with setting the 'CADICAL_RADIX_BUCKETS_ON_THE_HEAP' macro in order to avoid allocating the radix sort counters on the heap.

**Comment by srogatch** [comment]
Thanks, @arminbiere , I will try `CADICAL_API_TRACE` next. I'm afraid `valgrind` would be too slow, but let's give it a try too.
Your radix sort is now completely gone - I've replaced it with the following:
```
template<class I, class Rank> void rsort (I first, I last, Rank rank)
{
  typedef typename iterator_traits<I>::value_type T;
  //typedef typename Rank::Type R;

  assert (first <= last);
  const size_t n = last - first;
  if (n <= 1) return;

  constexpr int keyLen = sizeof(rank(*first));
  size_t counts[keyLen * 256];
  memset(counts, 0, sizeof(counts));
  for(I it=first; it != last; it++) {
    auto r = rank(*it);
    #pragma unroll 8
    for(int i=0; i<keyLen; i++) {
      const uint8_t b = uint8_t(r>>(i<<3));
      counts[b*keyLen + i]++;
    }
  }
  size_t offsets[keyLen] = {0};
  size_t tmp[keyLen];
  for(int i=0; i<256; i++) {
    #pragma unroll 8
    for(int j=0; j<keyLen; j++) {
      tmp[j] = offsets[j] + counts[i*keyLen+j];
    }
    #pragma unroll 8
    for(int j=0; j<keyLen; j++) {
      counts[i*keyLen+j] = offsets[j];
    }
    #pragma unroll 8
    for(int j=0; j<keyLen; j++) {
      offsets[j] = tmp[j];
    }
  }
  vector<T> cpy;
  cpy.resize(n);
  int i=0;
  for(; i+1<keyLen; i++) {
    for(I it=first; it != last; it++) {
      T elm = *it;
      auto r = rank(elm);
      const uint8_t b = uint8_t(r>>(i<<3));
      const int at = b*keyLen + i;
      cpy[counts[at]] = elm;
      counts[at]++;
    }
    i++;
    for(I it=cpy.begin(); it != cpy.end(); it++) {
      T elm = *it;
      auto r = rank(elm);
      const uint8_t b = uint8_t(r>>(i<<3));
      const int at = b*keyLen + i;
      first[counts[at]] = elm;
      counts[at]++;
    }
  }
  if(i<keyLen) {
    for(I it=first; it != last; it++) {
      T elm = *it;
      auto r = rank(elm);
      const uint8_t b = uint8_t(r>>(i<<3));
      const int at = b*keyLen + i;
      cpy[counts[at]] = elm;
      counts[at]++;
    }
    for (size_t i = 0; i < n; i++) {
      first[i] = cpy[i];
    }
  }

#ifndef NDEBUG
  for (I p = first; p + 1 != last; p++)
    assert (rank (p[0]) <= rank (p[1]));
#endif
}
```
I pre-loaded `jemalloc` built in debug mode like this:
`LD_PRELOAD=/usr/lib/llvm-13/lib/clang/13.0.1/lib/linux/libclang_rt.asan-x86_64.so:/usr/local/lib/libjemalloc.so.2 cbmc Sample2.c --trace --error-label success --symex-cache-dereferences`
Then I got another stack trace:
```
Solving with CaDiCaL 1.5.2
6349523 variables, 39638459 clauses
AddressSanitizer:DEADLYSIGNAL
=================================================================
==83681==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000ffff0 (pc 0x7f21b0f7b4d4 bp 0x000000000000 sp 0x7ffd8054b3b0 T0)
==83681==The signal is caused by a WRITE memory access.
    #0 0x7f21b0f7b4d4  (/usr/lib/llvm-13/lib/clang/13.0.1/lib/linux/libclang_rt.asan-x86_64.so+0x494d4)
    #1 0x7f21b1002c15 in operator delete(void*) (/usr/lib/llvm-13/lib/clang/13.0.1/lib/linux/libclang_rt.asan-x86_64.so+0xd0c15)
    #2 0x186f1c2 in void std::_Destroy<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> > >(std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:140:19
    #3 0x186f1c2 in void std::_Destroy_aux<false>::__destroy<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*>(std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*, std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:152:6
    #4 0x186f1c2 in void std::_Destroy<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*>(std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*, std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_construct.h:184:7
    #5 0x186f1c2 in void std::_Destroy<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*, std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> > >(std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*, std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*, std::allocator<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> > >&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/alloc_traits.h:746:7
    #6 0x186f1c2 in std::vector<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >, std::allocator<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> > > >::_M_erase_at_end(std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >*) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_vector.h:1796:6
    #7 0x186e6c7 in void CaDiCaL::erase_vector<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> > >(std::vector<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> >, std::allocator<std::vector<CaDiCaL::Clause*, std::allocator<CaDiCaL::Clause*> > > >&) /scratch/install/src/cadical/build/../src/util.hpp:83:5
    #8 0x190a1ee in CaDiCaL::Internal::subsume_round() /scratch/install/src/cadical/build/../src/subsume.cpp:547:3
    #9 0x190b79a in CaDiCaL::Internal::subsume(bool) /scratch/install/src/cadical/build/../src/subsume.cpp:586:5
    #10 0x19b114c in CaDiCaL::Internal::elim(bool) /scratch/install/src/cadical/build/../src/elim.cpp:846:5
    #11 0x1846e13 in CaDiCaL::Internal::cdcl_loop_with_inprocessing() /scratch/install/src/cadical/build/../src/internal.cpp:212:30
    #12 0x184b168 in CaDiCaL::Internal::solve(bool) /scratch/install/src/cadical/build/../src/internal.cpp:598:21
    #13 0x1839dc9 in CaDiCaL::External::solve(bool) /scratch/install/src/cadical/build/../src/external.cpp:268:23
    #14 0x1704cf6 in CaDiCaL::Solver::call_external_solve_and_check_results(bool) /scratch/install/src/cadical/build/../src/solver.cpp:602:29
    #15 0x1455323 in satcheck_cadicalt::do_prop_solve() (/usr/local/bin/cbmc+0x1455323)
    #16 0x15ae23f in prop_conv_solvert::dec_solve() /scratch/install/src/cbmc/src/solvers/prop/prop_conv_solver.cpp:456:15
    #17 0x1088232 in run_property_decider(incremental_goto_checkert::resultt&, std::map<dstringt, property_infot, std::less<dstringt>, std::allocator<std::pair<dstringt const, property_infot> > >&, goto_symex_property_decidert&, ui_message_handlert&, std::chrono::duration<double, std::ratio<1l, 1l> >, bool) /scratch/install/src/cbmc/src/goto-checker/bmc_util.cpp:404:62
    #18 0x109aad6 in multi_path_symex_checkert::operator()(std::map<dstringt, property_infot, std::less<dstringt>, std::allocator<std::pair<dstringt const, property_infot> > >&) /scratch/install/src/cbmc/src/goto-checker/multi_path_symex_checker.cpp:68:3
    #19 0xbe9d4a in all_properties_verifier_with_trace_storaget<multi_path_symex_checkert>::operator()() /scratch/install/src/cbmc/src/cbmc/../goto-checker/all_properties_verifier_with_trace_storage.h:43:27
    #20 0xbcec91 in cbmc_parse_optionst::doit() /scratch/install/src/cbmc/src/cbmc/cbmc_parse_options.cpp:778:26
    #21 0x1a1f1de in parse_options_baset::main() /scratch/install/src/cbmc/src/util/parse_options.cpp:100:12
    #22 0xbbc796 in main /scratch/install/src/cbmc/src/cbmc/cbmc_main.cpp:48:27
    #23 0x7f21b02b50b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16
    #24 0x7f855d in _start (/usr/local/bin/cbmc+0x7f855d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/llvm-13/lib/clang/13.0.1/lib/linux/libclang_rt.asan-x86_64.so+0x494d4) 
==83681==ABORTING
```

**Comment by srogatch** [comment]
Please, find the API trace here: https://www.dropbox.com/s/bvjplxsl6wl20ex/cadical_api_trace.txt.gz?dl=0 - there is a download button (arrow down) in the top right corner.
While generating the trace without sanitizers, but with `jemalloc` built in debug, I got the following:
```
Solving with CaDiCaL 1.5.2
6349523 variables, 39638459 clauses
cbmc: ../src/collect.cpp:177: void CaDiCaL::Internal::flush_watches(int, CaDiCaL::Watches &): Assertion `c->literals[!new_blit_pos] == lit' failed.
Aborted (core dumped)
```

**Comment by arminbiere** [comment]
Thanks, was running it with './configure -c -s && make && mobical trace' but could not reproduce your failure.  Also extracted the CNF from the trace with a simple script and was running this through CaDiCaL directly.  This also finished after approx. 2000 seconds (also with 'SAT').  So at the moment I suspect you have a memory issue on your side or due to some changes in semantics of C++ (I saw 'erase_vector' in one of your stack traces which I define in 'utils' and use to deallocate vector memory - a common trick in C++ - but not necessarily portable).  Can you reproduce the bug with your trace and your build of mobical?  Then I would need to know the exact build environment and version of CaDiCaL you are using.

**Comment by srogatch** [comment]
Thank you for investigating this. Yes, these formulas are most likely satisfiable and have many solutions so that there is a high probability of satisfying the formulas if substituting some variables randomly, though solvers do not find the solution quickly.
Here's my build script:
```
cd /scratch/install/src/jemalloc
export CFLAGS="-mavx2 -mfma -O3 -ggdb3"
export CXXFLAGS="-mavx2 -mfma -O3 -ggdb3"
export LDFLAGS="-rdynamic"
CC=clang-13 CXX=clang++-13 ./configure --enable-debug
make -j 128
sudo make install

cd /scratch/install/src/cadical
rm -rf build
CFLAGS="-mavx2 -mfma" \
  CXXFLAGS="-mavx2 -mfma" \
  CXX=clang++-13 CC=clang-13 ./configure --symbols --check
make -j 128

cd /scratch/install/src/cbmc
make -C src clean
export CFLAGS="-mavx2 -mfma -O3 -ggdb3"
export CXXFLAGS="-mavx2 -mfma -O3 -ggdb3"
make CADICAL=/scratch/install/src/cadical CC=clang-13 CXX=clang++-13 \
  LINKFLAGS="-rdynamic" \
  -j 128 -C src
sudo cp src/cbmc/cbmc /usr/local/bin/
```
I am building Cadical commit `ca9bff05c11bde5eae4912f9932871d1527e61d8` tagged as `rel-1.5.2`.

Can the issue arise from the interaction of CBMC and Cadical? I also didn't observe the crashes when putting the same DIMACS formula on input to Cadical as a file, but the linked program crashes when CBMC puts the formula to Cadical directly in memory.

I'll now run a memory check on my Ubuntu 20.04, and then `mobical`.

**Comment by srogatch** [comment]
Yes, it's a memory issue:
```
sudo memtester 210G 5
memtester version 4.3.0 (64-bit)
Copyright (C) 2001-2012 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 4096
pagesizemask is 0xfffffffffffff000
want 215040MB (225485783040 bytes)
got  215040MB (225485783040 bytes), trying mlock ...locked.
Loop 1/5:
  Stuck Address       : testing   0FAILURE: possible bad address line at offset 0x114139990.
Skipping to next test...
  Random Value        : FAILURE: 0x7f7c8122bfff665f != 0x7f7c8122bfff66df at offset 0x114139990.
FAILURE: 0x27ffa999ffcf6639 != 0x27ffa999ffcf66b9 at offset 0x11cbddae8.
FAILURE: 0xdf7fd1d9f77ed6dc != 0xdf7fd1d9f77ed69c at offset 0x6de3bf310.
FAILURE: 0x7bfdc07c7bcb15b1 != 0x7bfdc07c7bcb1591 at offset 0xba0957218.
FAILURE: 0xaaee91b0006637d != 0xaaee91b000663fd at offset 0x114139990.
FAILURE: 0x522dc1a04036631b != 0x522dc1a04036639b at offset 0x11cbddae8.
FAILURE: 0xaa75419941469fae != 0xaa75419943469fae at offset 0x4267ecb78.
FAILURE: 0x689f352bc84230f5 != 0x689f352bc8423075 at offset 0x4421e5c40.
FAILURE: 0xa2d6ca94c04de6a != 0xa2d6ca94c84de6a at offset 0x6735dd420.
FAILURE: 0xaaadb9e04887d3fe != 0xaaadb9e04887d3be at offset 0x6de3bf310.
FAILURE: 0xa1d67d3440a0c44 != 0xa1d67d344020c44 at offset 0xaa5c83ba8.
FAILURE: 0xe2fa845c4321093 != 0xe2fa845c43210b3 at offset 0xba0957218.
  Compare XOR         : FAILURE: 0x4bc3bc77d29d48a6 != 0x4bc3bc77d29d4926 at offset 0x114139990.
FAILURE: 0x934294fd12cd4844 != 0x934294fd12cd48c4 at offset 0x11cbddae8.
FAILURE: 0xeb8a14f613dd84d7 != 0xeb8a14f615dd84d7 at offset 0x4267ecb78.
FAILURE: 0xa9b408889ad9161e != 0xa9b408889ad9159e at offset 0x4421e5c40.
FAILURE: 0x4b4240061e9bc393 != 0x4b4240061f1bc393 at offset 0x6735dd420.
FAILURE: 0xebc28d3d1b1eb927 != 0xebc28d3d1b1eb8e7 at offset 0x6de3bf310.
FAILURE: 0xcb423b53645b153d != 0xcb423b53665b153d at offset 0x7ddc07128.
FAILURE: 0x4b323b3016a0f16d != 0x4b323b301698f16d at offset 0xaa5c83ba8.
FAILURE: 0x4f447ba296c8f5bc != 0x4f447ba296c8f5dc at offset 0xba0957218.
FAILURE: 0xebc469ac9cfd4e39 != 0xebc469ac9cfd4eb9 at offset 0x12b65be9e8.
FAILURE: 0x8b92564da71baaab != 0x8b92564da51baaab at offset 0x14deec16d8.
```
I'll fix this and try Cadical+CBMC again.

**Comment by arminbiere** [comment]
The instance is not that simple.  Neither Kissat nor Satch can find a solution running over night.  The 'mobical' run with the optimized (just './configure') build went through (again with 'gcc').  I will try now your build.

**Comment by arminbiere** [comment]
OK, I do not have a machine readily accessible which supports AVX2 and without that (removing the '-mavx2') the trace goes through.  So it most likely either AVX2 support of 'clang-13' which is buggy (in combination with -O3  and -ggd3) or some memory issue in CBMC.  In any case it is hard for me to figure that out.

Here is the test I was running:

```
$ time ./build/mobical ~/test/trace
m Model Based Tester for the CaDiCaL SAT Solver Library
m Copyright (c) 2018-2021 Armin Biere, Mathias Fleury, JKU Linz
m 
m Version 1.5.2 ca9bff05c11bde5eae4912f9932871d1527e61d8
m Ubuntu clang version 13.0.1-++20211102053001+d218ef07a072-1~exp1~20211102053531.17 -mfma -Wall -Wextra -O3 -ggdb3
m Wed Nov 3 11:19:02 CET 2021 Linux sili7 5.4.0-89-generic x86_64
m 
m using default time limit of 10 seconds
m using default space limit of 1024 MB
m reading single trace from input '/home/biere/test/trace'
m                                                           calls vars clauses
m ----------------------------------------------------------------------------
m input:       /home/biere/test/trace                       154029907  6349523 39638459  1
m ----------------------------------------------------------------------------
m generated 0 traces: 1 ok 0%, 0 failed 0%, 1 executed
m solved 1: 1 sat 100%, 0 unsat 0%, 0 incremental 0%

real	38m4,344s
user	35m39,401s
sys	0m29,190s
```
The sanitized version is still running (for 48 minutes already).

**Comment by arminbiere** [comment]
I figured that our cluster nodes support AVX2 and am running the trace there too.  You could also try switching off the arena with `solver.set ("arena", 0)`, because if there is a some interplay between CBMC and how CaDiCaL it might be due that complex code. The clause arena as this is pretty tricky memory allocation code - potentially also not completely non-alias optimization save, so a source for triggering issues due to advances compiler optimization in a new compiler.  You could test this by compiling with '-fno-strict-aliasing' and see whether after adding that the problem still exists on your side.

**Comment by arminbiere** [comment]
```$ time ./build/mobical ~/test/trace
m Model Based Tester for the CaDiCaL SAT Solver Library
m Copyright (c) 2018-2021 Armin Biere, Mathias Fleury, JKU Linz
m 
m Version 1.5.2 ca9bff05c11bde5eae4912f9932871d1527e61d8
m Ubuntu clang version 13.0.1-++20211102053001+d218ef07a072-1~exp1~20211102053531.17 -mfma -Wall -Wextra -O3 -ggdb3 -fsanitize=address
m Wed Nov 3 12:09:14 CET 2021 Linux sili7 5.4.0-89-generic x86_64
m 
m using default time limit of 10 seconds
m using default space limit of 1024 MB
m reading single trace from input '/home/biere/test/trace'
m                                                           calls vars clauses
m ----------------------------------------------------------------------------
m input:       /home/biere/test/trace                       154029907  6349523 39638459  1
m ----------------------------------------------------------------------------
m generated 0 traces: 1 ok 0%, 0 failed 0%, 1 executed
m solved 1: 1 sat 100%, 0 unsat 0%, 0 incremental 0%

real	81m55,381s
user	79m22,743s
sys	2m6,257s
```

**Comment by arminbiere** [comment]
On our cluster machine now with AVX2 there was no problem either:

```[runlim] version:               1.22
[runlim] host:                  c3n19
[runlim] time limit:            311040000 seconds
[runlim] real time limit:       311040000 seconds
[runlim] space limit:           128000 MB
[runlim] argv[0]:               ./mobical-avx2
[runlim] argv[1]:               cadical_api_trace.txt
[runlim] start:                 Wed Nov  3 13:15:58 2021
[runlim] child:                 363551
m Model Based Tester for the CaDiCaL SAT Solver Library
m Copyright (c) 2018-2021 Armin Biere, Mathias Fleury, JKU Linz
m 
m Version 1.5.2 ca9bff05c11bde5eae4912f9932871d1527e61d8
m Ubuntu clang version 13.0.1-++20211102053001+d218ef07a072-1~exp1~20211102053531.17 -mavx2 -mfma -Wall -Wextra -O3 -ggdb3
m Wed Nov 3 13:14:41 CET 2021 Linux sili7 5.4.0-89-generic x86_64
m 
m using default time limit of 10 seconds
m using default space limit of 1024 MB
m reading single trace from input 'cadical_api_trace.txt'
m                                                           calls vars clauses
m ----------------------------------------------------------------------------
[runlim] sample:                9.96 time, 10.02 real, 2278 MB
[runlim] sample:                19.96 time, 20.02 real, 4502 MB
[runlim] sample:                29.96 time, 30.02 real, 6815 MB
m input:       cadical_api_trace.txt                        154029907  6349523 39638459  1
[runlim] sample:                39.96 time, 40.01 real, 8427 MB
[runlim] sample:                49.96 time, 50.01 real, 10223 MB
[runlim] sample:                59.95 time, 60.01 real, 12029 MB
[runlim] sample:                69.95 time, 70.01 real, 13211 MB
[runlim] sample:                79.95 time, 80.01 real, 13258 MB
[runlim] sample:                89.95 time, 90.01 real, 13259 MB
[runlim] sample:                99.95 time, 100.01 real, 13259 MB
[runlim] sample:                109.95 time, 110.01 real, 13259 MB
[runlim] sample:                119.95 time, 120.01 real, 13259 MB
[runlim] sample:                129.95 time, 130.01 real, 13259 MB
[runlim] sample:                139.95 time, 140.01 real, 14122 MB
[runlim] sample:                149.95 time, 150.01 real, 14516 MB
[runlim] sample:                159.95 time, 160.01 real, 14378 MB
[runlim] sample:                169.95 time, 170.01 real, 14378 MB
[runlim] sample:                179.95 time, 180.01 real, 14378 MB
...
[runlim] sample:                2299.87 time, 2300.01 real, 13716 MB
[runlim] sample:                2309.87 time, 2310.01 real, 13716 MB
[runlim] sample:                2319.87 time, 2320.01 real, 13716 MB
[runlim] sample:                2329.87 time, 2330.01 real, 13716 MB
[runlim] sample:                2339.87 time, 2340.01 real, 13716 MB
m ----------------------------------------------------------------------------
m generated 0 traces: 1 ok 0%, 0 failed 0%, 1 executed
m solved 1: 1 sat 100%, 0 unsat 0%, 0 incremental 0%
[runlim] end:                   Wed Nov  3 13:55:04 2021
[runlim] status:                ok
[runlim] result:                0
[runlim] children:              1
[runlim] real:                  2345.96 seconds
[runlim] time:                  2345.78 seconds
[runlim] space:                 15892 MB
[runlim] samples:               23459
'''

**Comment by arminbiere** [comment]
Closed as it seems to have been an CBMC issue and is thus resolved.
